language: python
python: "3.5"

addons:
  apt:
    packages:
      - python-virtualenv
      - python3-dev
      - build-essential
      - awscli

install: python setup.py install

script:
  - echo "no tests!" # put testing scripts here once they're written

deploy:
  - provider: script
    script: chmod +x .travis/deploy_lambda.sh && .travis/deploy_lambda.sh
    skip_cleanup: true
    on:
      branch: lambda