language: python
python: "3.5"

addons:
  apt:
    packages:
      - python-virtualenv
      - python3-dev
      - build-essential

install: 
  - python setup.py install
  - pip install awscli

script:
  - echo "no tests!" # put testing scripts here once they're written
  - chmod +x .travis/build_lambda.sh && .travis/build_lambda.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'citygeo-airflow-databridge2'
    on:
      branch: master
    skip_cleanup: true
    local-dir: dist
    upload-dir: lambda
  - provider: lambda
    function_name: "databridge-etl-tools"
    region: "us-east-1"
    role: "arn:aws:iam::$AWS_ACCOUNT_ID:role/airflow-lambda"
    runtime: "python3.7"
    module_name: "function"
    handler_name: "handler"