sudo: required # Needed for ecr

language: python
python: "3.5"

addons:
  apt:
    packages:
      - python-virtualenv
      - python3-dev
      - build-essential
      - unzip
      - subversion

services:
  # Needed for ecr
  - docker

before_install:
  - chmod +x .travis/*.sh
  - .travis/before_install.sh

install: 
  # setuptools didn't play nicely with git dependencies so we'll have to just install from github
  - pip install git+https://github.com/CityOfPhiladelphia/databridge-etl-tools#egg=databridge_etl_tools[carto,postgres,dev]

script:
  # Needed to avoid bug with Travis using moto https://github.com/spulec/moto/issues/1771
  - export BOTO_CONFIG=/dev/null
  - .travis/run_tests.sh
  - .travis/build_lambda.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'citygeo-airflow-databridge2'
    on:
      branch: master
    skip_cleanup: true
    local-dir: dist
    upload-dir: lambda
  - provider: script
    script: .travis/deploy_lambda.sh
    on:
      branch: master
    skip_cleanup: true
  - provider: script
    script: .travis/deploy_ecr.sh
    on:
      branch: master
    skip_cleanup: true