language: python
python: "3.5"

addons:
  apt:
    packages:
      - python-virtualenv
      - python3-dev
      - build-essential

install: 
  - pip install git+https://github.com/CityOfPhiladelphia/databridge-etl-tools#egg=databridge_etl_tools --process-dependency-links
  - pip install awscli

script:
  - echo "no tests!" # put testing scripts here once they're written
  - chmod +x .travis/build_lambda.sh .travis/deploy_lambda.sh && .travis/build_lambda.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'citygeo-airflow-databridge2'
    on:
      branch: master
    skip_cleanup: true
    local-dir: dist
    upload-dir: lambda
  - provider: script
    script: bash .travis/deploy_lambda.sh
    on:
      branch: master