sudo: required # Needed for ecr

language: python
python: "3.5"

addons:
  apt:
    packages:
      - python-virtualenv
      - python3-dev
      - python-psycopg2
      - build-essential
      - unzip
      - subversion

services:
  # Needed for ecr
  - docker

before_install:
  - |
      if [ "$TRAVIS_BRANCH" = "test" ]; then
        export ENVIRONMENT="test"
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        export ENVIRONMENT="prod"
      fi
  - chmod +x .travis/*.sh
  - pip install awscli

install: 
  - pip install git+https://github.com/CityOfPhiladelphia/databridge-etl-tools.git@$TRAVIS_BRANCH#egg=databridge_etl_tools[carto,postgres,dev]

script:
  # Needed to avoid bug with Travis using moto https://github.com/spulec/moto/issues/1771
  - export BOTO_CONFIG=/dev/null
  - .travis/run_tests.sh
  - .travis/get_psycopg2.sh
  - .travis/build_lambda.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'citygeo-airflow-databridge2'
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|test$
    skip_cleanup: true
    local-dir: dist
    upload-dir: lambda
  - provider: script
    script: .travis/deploy_lambda.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|test$
    skip_cleanup: true
  - provider: script
    script: .travis/deploy_ecr.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|test$
    skip_cleanup: true