FROM apache/airflow:3.1.0

# See https://airflow.apache.org/docs/docker-stack/build.html
USER root

# Add our worker users custom binaries to the path, some python packages are installed here.
# ENV PATH="/home/worker/.local/bin:${PATH}"

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
#ENV TERM linux

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    libpq-dev \
    libpq5 \
    apt-utils \
    build-essential \
    ca-certificates \
    curl \
    git \
    gnupg \
    lsb-release \
    wget \
    unzip \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

COPY pyproject.toml ./pyproject.toml
COPY databridge_etl_tools ./databridge_etl_tools

# Python syntax check
RUN python -m compileall ./databridge_etl_tools

# Install databridge-etl-tools using pyproject.toml
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" .