FROM python:3.11-slim-trixie

# Add our worker users custom binaries to the path, some python packages are installed here.
ENV PATH="/home/worker/.local/bin:${PATH}"

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

RUN useradd -ms /bin/bash worker

RUN apt-get update && \
  apt-get install -yqq --no-install-recommends \
  libpq-dev \
  apt-utils \
  build-essential \
  ca-certificates \
  curl \
  git \
  gnupg \
  lsb-release \
  wget \
  unzip

# Cleanup
RUN apt-get remove --purge -yqq $buildDeps \
  && apt-get clean \
  && rm -rf \
  /var/lib/apt/lists/* \
  /tmp/* \
  /var/tmp/* \
  /usr/share/man \
  /usr/share/doc \
  /usr/share/doc-base

USER worker
WORKDIR /home/worker/

COPY --chown=worker:root scripts/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Put our pip installs, but not our own module install, here first so we can more rapidly build.
# pip installs take the longest.
RUN pip install pip --upgrade \
  && pip install setuptools --upgrade
# Funny command to install dependencies directly from pyproject.toml, that way we don't have to
# maintain a separate requirements.txt file.
COPY --chown=worker:root pyproject.toml ./pyproject.toml
RUN python - <<'PY' >/tmp/pyproject-toml-reqs.txt
import importlib
import tomllib as tl
with open("pyproject.toml","rb") as f:
    deps = tl.load(f)["project"]["dependencies"]
print("\n".join(deps))
PY
RUN pip install --no-cache-dir -r /tmp/pyproject-toml-reqs.txt

COPY --chown=worker:root tests/ ./tests/
COPY --chown=worker:root databridge_etl_tools ./databridge_etl_tools

# Python syntax check
RUN python -m compileall ./databridge_etl_tools

# Install databridge-etl-tools using pyproject.toml
RUN pip install .

# Set aws access keys as an env var for use with boto3
# do this under the worker user.
# These are passed in via --build-arg at build time.
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ENTRYPOINT ["/home/worker/entrypoint.sh"]